#!/bin/sh
set -eu

if [ -f .sig ]; then
    RED='\033[0;31m'
    NC='\033[0m' # No Color

    sig_tmp=.sig.tmp
    # Remove space around = & source to get the required name & email
    sed 's/ *= */=/g' .sig >"$sig_tmp"
    . ./"$sig_tmp"
    rm "$sig_tmp"
    if [ -n "${name-}" ] && [ "$GIT_AUTHOR_NAME" != "$name" ]; then
        echo "Required author name for this repo: $name"
        git config --global user.name "$name"
        wrong=true
    fi
    if [ -n "${email-}" ] && [ "$GIT_AUTHOR_EMAIL" != "$email" ]; then
        echo "Required author email for this repo: $email"
        git config --global user.email "$email"
        wrong=true
    fi
    if [ "${wrong-}" = "true" ]; then
        printf "${RED}Configured git signature accordingly, please re-commit${NC}\n"
        exit 1
    fi
fi
